# Generated by Django 5.0.6 on 2024-06-15 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('store_link', models.URLField()),
                ('image_url', models.URLField()),
                ('sku', models.CharField(max_length=100)),
                ('clothing_type', models.CharField(choices=[('top', 'Top'), ('bottom', 'Bottom'), ('full', 'Full')], max_length=50)),
                ('clothing_category', models.CharField(max_length=50)),
                ('manufacturer_name', models.CharField(max_length=255)),
                ('country_of_origin', models.CharField(max_length=100)),
            ],
        ),
    ]
