# Generated by Django 5.0.6 on 2024-06-26 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='colour',
            field=models.CharField(default='unknown', max_length=100),
        ),
    ]
