# Generated by Django 5.0.6 on 2024-07-07 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='clothing_type',
            field=models.CharField(choices=[('upper_body', 'Upper Body'), ('lower_body', 'Lower Body'), ('dresses', 'Dresses')], default='upper_body', max_length=50),
        ),
    ]
