# Generated by Django 5.0.6 on 2024-07-17 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_product_clothing_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='clothing_category',
            field=models.CharField(choices=[('dress', 'Dress'), ('top', 'Top'), ('jeans', 'Jeans'), ('jumpsuit', 'Jumpsuit'), ('short', 'short'), ('jacket', 'Jacket'), ('sweatpants', 'Sweatpants'), ('skirt', 'Skirt'), ('sweater', 'Sweater'), ('pants', 'Pants'), ('leggings', 'Leggings'), ('coat', 'Coat')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='colour',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='country_of_origin',
            field=models.CharField(choices=[('usa', 'USA'), ('united_kingdom', 'United Kingdom'), ('germany', 'Germany'), ('brazil', 'Brazil'), ('italy', 'Italy'), ('france', 'France'), ('spain', 'Spain'), ('poland', 'Poland'), ('czech_republic', 'Czech Republic'), ('slovakia', 'Slovakia')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacturer_name',
            field=models.CharField(max_length=17),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=21),
        ),
        migrations.AlterField(
            model_name='product',
            name='store_link',
            field=models.URLField(max_length=1000),
        ),
    ]
