# Generated by Django 5.0.6 on 2024-09-09 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_remove_product_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='country_of_origin',
            field=models.CharField(choices=[('usa', 'USA'), ('united_kingdom', 'United Kingdom'), ('germany', 'Germany'), ('brazil', 'Brazil'), ('italy', 'Italy'), ('france', 'France'), ('spain', 'Spain'), ('poland', 'Poland'), ('czech_republic', 'Czech Republic'), ('slovakia', 'Slovakia')], default='usa', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default='Default Name', max_length=21),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(default='00000', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='clothing_category',
            field=models.CharField(choices=[('dress', 'Dress'), ('top', 'Top'), ('jeans', 'Jeans'), ('jumpsuit', 'Jumpsuit'), ('short', 'Short'), ('jacket', 'Jacket'), ('sweatpants', 'Sweatpants'), ('skirt', 'Skirt'), ('sweater', 'Sweater'), ('pants', 'Pants'), ('leggings', 'Leggings'), ('coat', 'Coat')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
