# Generated by Django 5.0.6 on 2024-09-09 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_product_country_of_origin_product_name_product_sku_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='country_of_origin',
        ),
        migrations.AlterField(
            model_name='product',
            name='colour',
            field=models.CharField(choices=[('light', 'Light')], default='light', max_length=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
