# Generated by Django 5.0.6 on 2024-07-18 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_favoriteitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='subscription_type',
            field=models.CharField(choices=[('free', 'Free Plan'), ('basic', 'Basic Plan'), ('pro', 'Pro Plan'), ('premium', 'Premium Plan'), ('basic_annual', 'Basic Annual Plan'), ('pro_annual', 'Pro Annual Plan'), ('premium_annual', 'Premium Annual Plan')], default='free', max_length=20),
        ),
    ]
