# Generated by Django 5.0.6 on 2024-07-25 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_customuser_reset_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='confirmation_code_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='reset_token_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
