# Generated by Django 5.0.6 on 2024-08-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_delete_temporaryregistration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='google_play_order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='google_play_purchase_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
